stages:
  - build
  - deploy

variables:
  JAVA_VERSION: "21"
  MAVEN_VERSION: "3.9"
  PROD_IMAGE: docker.fream.pl/hello-poland/hpl/backend:_prod_$CI_COMMIT_SHA
  PROD_CONTAINER_NAME: hello_poland

Build for production server:
  stage: build
  before_script:
    - . envcfg
    - envcfg -p
  script:
    - mvn -Dlocal.maven.build.properties=${PROD_MAVEN_PROPERTIES} -Dmaven.test.skip=true clean package -U
    - docker build -t $PROD_IMAGE .
    - docker push $PROD_IMAGE
    - docker image rm $PROD_IMAGE
  tags:
    - shell-executor

Deploy on prod server:
  stage: deploy
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $PROD_IMAGE
    - docker ps -aq --filter name=$PROD_CONTAINER_NAME | grep -q . && docker stop $PROD_CONTAINER_NAME && docker rm $PROD_CONTAINER_NAME
    - docker run -d -p 127.0.0.1:8280:8080 -v HELLO_DMS:/DMS -v ${PROD_RUNTIME_PROPERTIES}:/opt/jboss/wildfly/standalone/deployments/local.runtime.properties --name $PROD_CONTAINER_NAME $PROD_IMAGE
  tags:
    - hpl-prod
  when: manual
