version: '3'
services:
  database:
    container_name: hpl_database
    image: postgres:alpine
    volumes:
      - ${FRM_HPL_DB_CREATE_SCRIPT_DIR}:${FRM_HPL_DOCKER_DB_ENTRYPOINT_DIR}/${FRM_HPL_DB_CREATE_SCRIPT}
      - hellopoland-hpl-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  backend:
    container_name: hpl_backend
    image: "${FRM_HPL_TEST_DOCKER_BACKEND_IMAGE}"
    volumes:
      - dms:/opt/data/dms
      - ${FRM_HPL_DOCKER_COMPOSE_LOCAL_RUNTIME_PROP_DIR}:/opt/local.runtime.properties
    ports:
      - 8361:8080
    depends_on:
      - database
volumes:
  hellopoland-hpl-pgdata:
  dms:
