<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>pl.hellopoland</groupId>
	<artifactId>hellopoland</artifactId>
	<version>1.0.0</version>
	<packaging>war</packaging>
	<name>Hello Poland</name>
	<description>Hello Poland backend project</description>

	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<failOnMissingWebXml>false</failOnMissingWebXml>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<local.properties>src/main/resources/maven.build.properties</local.properties>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>5.3.10.Final</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.ws.cxf</groupId>
			<artifactId>jbossws-cxf-client</artifactId>
			<version>5.2.4.Final</version>
			<exclusions>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.geronimo.javamail</groupId>
					<artifactId>geronimo-javamail_1.4_mail</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>8.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-dto</artifactId>
			<version>1.0.44-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>pl.fream.commons</groupId>
			<artifactId>fulltext-search-dialect</artifactId>
			<version>0.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.microprofile.health</groupId>
			<artifactId>microprofile-health-api</artifactId>
			<version>1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt</artifactId>
			<version>0.9.1</version>
		</dependency>
		<!-- GoogleAPIConnector -->
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.30.2</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2</artifactId>
			<version>2.0.9</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-servlet-initializer</artifactId>
			<version>2.0.9</version>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.2.8</version>
			<scope>runtime</scope>
		</dependency>
	</dependencies>

	<build>
		<finalName>hellopoland</finalName>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>properties-maven-plugin</artifactId>
				<version>1.0.0</version>
				<goals />
				<executions>
					<execution>
						<id>read.properties</id>
						<phase>initialize</phase>
						<goals>
							<goal>read-project-properties</goal>
						</goals>
						<configuration>
							<quiet>true</quiet>
							<files>
								<file>src/main/resources/maven.build.properties</file>
								<file>${local.properties}</file>
							</files>
							<encoding>UTF-8</encoding>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>**/*.jar</exclude>
					<exclude>cwebp/**</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/*.jar</include>
					<include>cwebp/**</include>
				</includes>
			</resource>
		</resources>
	</build>

	<repositories>
		<repository>
			<id>fream-nexus-snapshots</id>
			<url>https://packages.fream.pl/repository/maven-fream-snapshots</url>
		</repository>
		<repository>
			<id>fream-nexus-releases</id>
			<url>https://packages.fream.pl/repository/maven-fream-releases</url>
		</repository>
		<repository>
			<id>redhat ga</id>
			<url>https://maven.repository.redhat.com/ga</url>
		</repository>
	</repositories>
</project>