<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>pl.hellopoland</groupId>
	<artifactId>hellopoland</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>Hello Poland</name>
	<description>Hello Poland backend project</description>

	<properties>
		<maven.compiler.source>10</maven.compiler.source>
		<maven.compiler.target>10</maven.compiler.target>
		<failOnMissingWebXml>false</failOnMissingWebXml>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<parent.basedir>.</parent.basedir>
		<security.domain>hellopoland</security.domain>
		<local.properties>etc/${user.name}.config.properties</local.properties>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>javax</groupId>
				<artifactId>javaee-api</artifactId>
				<version>8.0</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>pl.hellopoland</groupId>
				<artifactId>hellopoland-dto</artifactId>
				<version>0.4.13-SNAPSHOT</version>
			</dependency>
		</dependencies>
	</dependencyManagement>


	<dependencies>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt</artifactId>
			<version>0.9.0</version>
		</dependency>

		<dependency>
			<groupId>org.picketbox</groupId>
			<artifactId>picketbox</artifactId>
			<version>5.0.2.Final</version>
			<scope>provided</scope>
		</dependency>

		<!-- GoogleAPIConnector -->
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.23.0</version>
		</dependency>

		<!-- WooCommerceAPIConnector -->
		<dependency>
			<groupId>com.icoderman</groupId>
			<artifactId>wc-api-java</artifactId>
			<version>1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.2</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-servlet-initializer</artifactId>
			<version>2.0.2</version>
		</dependency>

		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-dto</artifactId>
		</dependency>
	</dependencies>

	<build>
		<finalName>hellopoland</finalName>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>properties-maven-plugin</artifactId>
				<version>1.0.0</version>
				<goals />
				<executions>
					<execution>
						<id>read.properties</id>
						<phase>initialize</phase>
						<goals>
							<goal>read-project-properties</goal>
						</goals>
						<configuration>
							<quiet>true</quiet>
							<files>
								<file>etc/config.properties</file>
								<file>etc/${user.name}.config.properties</file>
								<file>${local.properties}</file>
							</files>
							<encoding>UTF-8</encoding>
						</configuration>
					</execution>
					<execution>
						<id>write.properties</id>
						<phase>initialize</phase>
						<goals>
							<goal>write-project-properties</goal>
						</goals>
						<configuration>
							<outputFile>${project.build.outputDirectory}/config.properties</outputFile>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.liquibase</groupId>
				<artifactId>liquibase-maven-plugin</artifactId>
				<version>3.6.2</version>
				<configuration>
					<propertyFile>${local.properties}</propertyFile>
				</configuration>
				<executions>
					<execution>
						<id>db_install</id>
						<phase>install</phase>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.postgresql</groupId>
						<artifactId>postgresql</artifactId>
						<version>42.2.4</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<excludes>
					<exclude>**/*.jar</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/*.jar</include>
				</includes>
			</resource>
		</resources>
	</build>

	<profiles>
		<profile>
			<id>copy-wildfly-files</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.0.2</version>
						<executions>
							<execution>
								<phase>initialize</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${wildfly.home}</outputDirectory>
									<resources>
										<resource>
											<directory>${project.build.directory}/classes/wildfly</directory>
											<filtering>false</filtering>
											<includes>
												<include>**/*.jar</include>
											</includes>
										</resource>
										<resource>
											<directory>${project.build.directory}/classes/wildfly</directory>
											<filtering>true</filtering>
											<excludes>
												<exclude>**/*.jar</exclude>
											</excludes>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

	<repositories>
		<repository>
			<id>fream-nexus</id>
			<url>https://packages.fream.pl/repository/maven-fream-snapshots</url>
		</repository>
	</repositories>
</project>
