hibernate.hbm2ddl.auto=update
hibernate.show.sql=false
hibernate.function_contributors=pl.hellopoland.config.fulltextsearch.PgFunctionContributor
jakarta.persistence.jdbc.host=172.17.0.1
jakarta.persistence.jdbc.port=5432
jakarta.persistence.jdbc.database=hellopoland
jakarta.persistence.jdbc.user=hellopoland
jakarta.persistence.jdbc.password=hpl-prod
