hibernate.hbm2ddl.auto=update
hibernate.show.sql=false
jakarta.persistence.jdbc.host=172.17.0.1
jakarta.persistence.jdbc.port=5432
jakarta.persistence.jdbc.database=hellopoland_tst
jakarta.persistence.jdbc.user=hellopoland_tst
jakarta.persistence.jdbc.password=hellopoland_tst
