hibernate.hbm2ddl.auto=update
hibernate.show.sql=true
jakarta.persistence.jdbc.host=localhost
jakarta.persistence.jdbc.port=5432
jakarta.persistence.jdbc.database=hellopoland
jakarta.persistence.jdbc.user=hellopoland
jakarta.persistence.jdbc.password=hellopoland
