db.filler.run=false

resteasy.preferJacksonOverJsonB=false
mail.smtp.enabled=false
mail.username=hpt@fream.pl
mail.password=JbmU4lMo
mail.smtp.host=s43.linuxpl.com
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

przelewy24.confirmation.endpoint=https://sandbox.przelewy24.pl/trnVerify
przelewy24.crc=611e97ebd30f7be3
przelewy24.merchantId=71852
przelewy24.posId=71937
przelewy24.isSandbox=true

jwt.access.token.validity.millis=1800000
jwt.refresh.token.validity.millis=2592000000
jwt.access.token.secret.key=RqPW5zbChtPmzgSekctYdAWrHLNkBpDvK6meDtA3pDtAYKFBXH4UEjLvjdN9rfjkfS6LMpT2wvWvxg9kn38Fhw6qMSG2ZUzPx2tsrMcV8PsvCLx6BZVK5tLCakffCBy4
jwt.refresh.token.secret.key=D6KxAUe98wKdqkTrvNb2hYEtAaWnmjceX7mn7z7BruXmCmC3WUtCFQGxa3krhb9fcVfcy2TppCNKPWGjarbh6C5PdKzNWeNe3GDrP9rvsFt8dbJqWTFU3Am2NFnXSqLh

#base.url=https://hpl.fream.pl/api/v1
base.url=http://localhost:8080/hellopoland/v1
hpt.cloud.url=http://localhost:8080/helloticket

FB.fanpage.id=316534255768958
FB.page.access.token=EAAElpgWU2WgBAOgZCLHd81ZBo7J5ZBzPhEM0KboDw5mfZALo7nercwbAMtszkSLqnJZBbI23ZB4f3UvYC0ajBXrZCHfrskafZANZCk9ZBBRVOWUuKkzLUA4OUHM8PGTiTNheGR1hmIWoCZBykaEOLByZA9mZCXt0YGwQpZAScymkSaOWevDkvIyXo9WWpt
FB.posts.fields.query.param=id,application,call_to_action,caption,created_time,description,feed_targeting,from,full_picture,icon,is_hidden,is_published,link,message,message_tags,name,object_id,permalink_url,picture,place,privacy,properties,shares,source,status_type,targeting,type,updated_time

mail.hellopoland.biuro=dawid@fream.pl

sendInBlue.secret.key=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
sendInBlue.list.id=4
sendInBlue.confirmation.template.id=3

dms.root.path=/DMS
