alter table tag
  add column if not exists promotional boolean not null default false;

create table if not exists promotion_campaign (
  id bigint generated by default as identity not null,
  name varchar(255) not null,
  promotion_type varchar(32) not null,
  status varchar(32) not null default 'DRAFT',
  scope_type varchar(32) not null,
  valid_from timestamp(6) not null,
  valid_to timestamp(6) not null,
  global_limit integer null,
  code_limit integer null,
  customer_limit integer null,
  daily_limit integer null,
  required_ticket_quantity integer null,
  granted_ticket_quantity integer null,
  reserved_redemptions_count integer not null default 0,
  used_redemptions_count integer not null default 0,
  discount_percent numeric(5,2) null,
  discount_amount_gross integer null,
  created_at timestamp(6) not null default now(),
  updated_at timestamp(6) null,
  created_by bigint null,
  updated_by bigint null,
  constraint promotion_campaign_pkey primary key (id),
  constraint promotion_campaign_type_check
    check (promotion_type in ('TICKET', 'PERCENT', 'AMOUNT')),
  constraint promotion_campaign_status_check
    check (status in ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
  constraint promotion_campaign_scope_type_check
    check (scope_type in ('MANUAL', 'TAG', 'GLOBAL')),
  constraint promotion_campaign_dates_check
    check (valid_to >= valid_from),
  constraint promotion_campaign_ticket_not_global_check
    check (promotion_type <> 'TICKET' or scope_type <> 'GLOBAL'),
  constraint promotion_campaign_global_limit_check
    check (global_limit is null or global_limit > 0),
  constraint promotion_campaign_code_limit_check
    check (code_limit is null or code_limit > 0),
  constraint promotion_campaign_customer_limit_check
    check (customer_limit is null or customer_limit > 0),
  constraint promotion_campaign_daily_limit_check
    check (daily_limit is null or daily_limit > 0),
  constraint promotion_campaign_required_ticket_quantity_check
    check (required_ticket_quantity is null or required_ticket_quantity > 0),
  constraint promotion_campaign_granted_ticket_quantity_check
    check (granted_ticket_quantity is null or granted_ticket_quantity > 0),
  constraint promotion_campaign_reserved_count_check
    check (reserved_redemptions_count >= 0),
  constraint promotion_campaign_used_count_check
    check (used_redemptions_count >= 0),
  constraint promotion_campaign_discount_percent_check
    check (discount_percent is null or (discount_percent > 0 and discount_percent <= 100)),
  constraint promotion_campaign_discount_amount_check
    check (discount_amount_gross is null or discount_amount_gross > 0),
  constraint promotion_campaign_created_by_fk
    foreign key (created_by) references users(id),
  constraint promotion_campaign_updated_by_fk
    foreign key (updated_by) references users(id)
);

alter table promotion_campaign
  add column if not exists required_ticket_quantity integer;

alter table promotion_campaign
  add column if not exists granted_ticket_quantity integer;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'promotion_campaign_required_ticket_quantity_check'
  ) then
    alter table promotion_campaign
      add constraint promotion_campaign_required_ticket_quantity_check
      check (required_ticket_quantity is null or required_ticket_quantity > 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'promotion_campaign_granted_ticket_quantity_check'
  ) then
    alter table promotion_campaign
      add constraint promotion_campaign_granted_ticket_quantity_check
      check (granted_ticket_quantity is null or granted_ticket_quantity > 0);
  end if;
end $$;

create table if not exists promotion_campaign_tag (
  promotion_campaign_id bigint not null,
  tag_id bigint not null,
  active boolean not null default true,
  created_at timestamp(6) not null default now(),
  constraint promotion_campaign_tag_pkey
    primary key (promotion_campaign_id, tag_id),
  constraint promotion_campaign_tag_campaign_fk
    foreign key (promotion_campaign_id) references promotion_campaign(id),
  constraint promotion_campaign_tag_tag_fk
    foreign key (tag_id) references tag(id)
);

create table if not exists promotion_campaign_sightevent (
  id bigint generated by default as identity not null,
  promotion_campaign_id bigint not null,
  sightevent_id bigint not null,
  active boolean not null default true,
  source varchar(32) not null default 'MANUAL',
  source_tag_id bigint null,
  hpt_sight_event_id bigint null,
  hpt_atna_id bigint null,
  hpt_ticket_definition_id bigint null,
  hpt_ticket_pool_definition_id bigint null,
  ticket_pool_status varchar(32) not null default 'NOT_REQUIRED',
  created_at timestamp(6) not null default now(),
  updated_at timestamp(6) null,
  constraint promotion_campaign_sightevent_pkey primary key (id),
  constraint promotion_campaign_sightevent_unique
    unique (promotion_campaign_id, sightevent_id),
  constraint promotion_campaign_sightevent_source_check
    check (source in ('MANUAL', 'TAG')),
  constraint promotion_campaign_sightevent_source_tag_check
    check (source <> 'TAG' or source_tag_id is not null),
  constraint promotion_campaign_sightevent_pool_status_check
    check (ticket_pool_status in ('NOT_REQUIRED', 'NOT_CREATED', 'CONFIG_REQUIRED', 'CREATED', 'ERROR')),
  constraint promotion_campaign_sightevent_campaign_fk
    foreign key (promotion_campaign_id) references promotion_campaign(id),
  constraint promotion_campaign_sightevent_sightevent_fk
    foreign key (sightevent_id) references sightevent(id),
  constraint promotion_campaign_sightevent_source_tag_fk
    foreign key (source_tag_id) references tag(id)
);

alter table promotion_campaign_sightevent
  add column if not exists hpt_atna_id bigint;

create table if not exists promotion_code_batch (
  id bigint generated by default as identity not null,
  promotion_campaign_id bigint not null,
  source varchar(32) not null,
  file_name varchar(255) null,
  codes_count integer not null default 0,
  created_at timestamp(6) not null default now(),
  created_by bigint null,
  constraint promotion_code_batch_pkey primary key (id),
  constraint promotion_code_batch_source_check
    check (source in ('GENERATED', 'IMPORT')),
  constraint promotion_code_batch_codes_count_check
    check (codes_count >= 0),
  constraint promotion_code_batch_campaign_fk
    foreign key (promotion_campaign_id) references promotion_campaign(id),
  constraint promotion_code_batch_created_by_fk
    foreign key (created_by) references users(id)
);

create table if not exists promotion_code (
  id bigint generated by default as identity not null,
  promotion_campaign_id bigint not null,
  promotion_code_batch_id bigint null,
  code varchar(255) not null,
  code_type varchar(32) not null,
  status varchar(32) not null default 'ACTIVE',
  max_redemptions integer null,
  max_redemptions_per_customer integer null,
  max_redemptions_per_day integer null,
  reserved_redemptions_count integer not null default 0,
  used_redemptions_count integer not null default 0,
  reserved_until timestamp(6) null,
  created_at timestamp(6) not null default now(),
  updated_at timestamp(6) null,
  disabled_at timestamp(6) null,
  constraint promotion_code_pkey primary key (id),
  constraint promotion_code_code_key unique (code),
  constraint promotion_code_type_check
    check (code_type in ('ONE_TIME', 'FIXED')),
  constraint promotion_code_status_check
    check (status in ('ACTIVE', 'RESERVED', 'USED', 'DISABLED')),
  constraint promotion_code_fixed_status_check
    check (code_type <> 'FIXED' or status in ('ACTIVE', 'DISABLED')),
  constraint promotion_code_max_redemptions_check
    check (max_redemptions is null or max_redemptions > 0),
  constraint promotion_code_max_redemptions_customer_check
    check (max_redemptions_per_customer is null or max_redemptions_per_customer > 0),
  constraint promotion_code_max_redemptions_day_check
    check (max_redemptions_per_day is null or max_redemptions_per_day > 0),
  constraint promotion_code_reserved_count_check
    check (reserved_redemptions_count >= 0),
  constraint promotion_code_used_count_check
    check (used_redemptions_count >= 0),
  constraint promotion_code_one_time_limit_check
    check (code_type <> 'ONE_TIME' or max_redemptions is null or max_redemptions = 1),
  constraint promotion_code_campaign_fk
    foreign key (promotion_campaign_id) references promotion_campaign(id),
  constraint promotion_code_batch_fk
    foreign key (promotion_code_batch_id) references promotion_code_batch(id)
);

create table if not exists promotion_code_redemption (
  id bigint generated by default as identity not null,
  promotion_campaign_id bigint not null,
  promotion_code_id bigint not null,
  promotion_campaign_sightevent_id bigint null,
  sightevent_id bigint null,
  order_id bigint null,
  orderentry_id bigint null,
  user_id bigint null,
  status varchar(32) not null default 'RESERVED',
  reservation_token varchar(255) null,
  reserved_at timestamp(6) not null default now(),
  reserved_until timestamp(6) null,
  used_at timestamp(6) null,
  released_at timestamp(6) null,
  code_snapshot varchar(255) not null,
  promotion_name_snapshot varchar(255) not null,
  promotion_type_snapshot varchar(32) not null,
  discount_percent numeric(5,2) null,
  discount_amount_gross integer null,
  hpt_ticket_definition_id bigint null,
  hpt_ticket_pool_definition_id bigint null,
  created_at timestamp(6) not null default now(),
  updated_at timestamp(6) null,
  constraint promotion_code_redemption_pkey primary key (id),
  constraint promotion_code_redemption_reservation_token_key unique (reservation_token),
  constraint promotion_code_redemption_status_check
    check (status in ('RESERVED', 'USED', 'RELEASED', 'CANCELLED', 'EXPIRED')),
  constraint promotion_code_redemption_type_snapshot_check
    check (promotion_type_snapshot in ('TICKET', 'PERCENT', 'AMOUNT')),
  constraint promotion_code_redemption_discount_percent_check
    check (discount_percent is null or (discount_percent > 0 and discount_percent <= 100)),
  constraint promotion_code_redemption_discount_amount_check
    check (discount_amount_gross is null or discount_amount_gross > 0),
  constraint promotion_code_redemption_campaign_fk
    foreign key (promotion_campaign_id) references promotion_campaign(id),
  constraint promotion_code_redemption_code_fk
    foreign key (promotion_code_id) references promotion_code(id),
  constraint promotion_code_redemption_campaign_sightevent_fk
    foreign key (promotion_campaign_sightevent_id) references promotion_campaign_sightevent(id),
  constraint promotion_code_redemption_sightevent_fk
    foreign key (sightevent_id) references sightevent(id),
  constraint promotion_code_redemption_order_fk
    foreign key (order_id) references orders(id),
  constraint promotion_code_redemption_orderentry_fk
    foreign key (orderentry_id) references orderentry(id),
  constraint promotion_code_redemption_user_fk
    foreign key (user_id) references users(id)
);

create index if not exists promotion_campaign_status_dates_idx
  on promotion_campaign (status, valid_from, valid_to);

create index if not exists promotion_campaign_type_idx
  on promotion_campaign (promotion_type);

create index if not exists promotion_campaign_tag_tag_idx
  on promotion_campaign_tag (tag_id);

create index if not exists promotion_campaign_sightevent_sightevent_idx
  on promotion_campaign_sightevent (sightevent_id);

create index if not exists promotion_campaign_sightevent_active_idx
  on promotion_campaign_sightevent (promotion_campaign_id, active);

create index if not exists promotion_code_campaign_status_idx
  on promotion_code (promotion_campaign_id, status);

create index if not exists promotion_code_batch_campaign_idx
  on promotion_code_batch (promotion_campaign_id);

create index if not exists promotion_code_redemption_code_status_idx
  on promotion_code_redemption (promotion_code_id, status);

create index if not exists promotion_code_redemption_campaign_status_idx
  on promotion_code_redemption (promotion_campaign_id, status);

create index if not exists promotion_code_redemption_order_idx
  on promotion_code_redemption (order_id);

create index if not exists promotion_code_redemption_orderentry_idx
  on promotion_code_redemption (orderentry_id);

create index if not exists promotion_code_redemption_sightevent_idx
  on promotion_code_redemption (sightevent_id);
