BEGIN;

ALTER TABLE userrole DROP CONSTRAINT IF EXISTS userrole_role_check;
ALTER TABLE userrole ADD CONSTRAINT userrole_role_check CHECK (role IN (
  'ROOT', 'ADMIN', 'HELPDESK_PARTNER_MANAGER', 'HELPDESK_CONTENT_MANAGER',
  'HELPDESK_SUPPORT', 'HELPDESK_TECHNICAL', 'PARTNER', 'PARTNER_ADMIN',
  'PARTNER_SALESMAN', 'SALESMAN', 'USHER', 'USER', 'partner'
));

CREATE TABLE IF NOT EXISTS technical_operation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id varchar(36) NOT NULL UNIQUE,
  actor varchar(255) NOT NULL,
  reason varchar(250) NOT NULL,
  operation varchar(64) NOT NULL,
  status varchar(32) NOT NULL CHECK (status IN ('REQUESTED', 'RUNNING', 'SUCCEEDED', 'SKIPPED', 'FAILED')),
  requested_at timestamp NOT NULL,
  started_at timestamp NULL,
  finished_at timestamp NULL,
  result_message varchar(2000) NULL
);

DO $$
DECLARE
  operator_id bigint;
  operator_count integer;
BEGIN
  SELECT count(*), min(id)
    INTO operator_count, operator_id
    FROM users
   WHERE lower(email) = 'piotr.dzidowski@coigdzie.pl'
     AND deleted = false;

  IF operator_count <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one active user piotr.dzidowski@coigdzie.pl, found %', operator_count;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM userrole
     WHERE user_id = operator_id
       AND role = 'HELPDESK_TECHNICAL'
  ) THEN
    INSERT INTO userrole (role, user_id)
    VALUES ('HELPDESK_TECHNICAL', operator_id);
  END IF;
END $$;

COMMIT;
