outputChangeLogFile=src/main/resources/database/changeLog.xml
diffChangeLogFile=src/main/resources/database/diff-changeLog.xml
changeLogFile=src/main/resources/database/input-changeLog.xml
driver=org.postgresql.Driver

url=jdbc:postgresql://localhost:5432/hellopoland
username=hellopoland
password=hellopoland

referenceUrl=jdbc:postgresql://localhost:5432/hellopoland_ref
referenceUsername=hellopoland
referencePassword=hellopoland