datasource.driver=postgresql
datasource.database.host=localhost
datasource.database.port=5432
datasource.database.name=hellopoland
datasource.database.user=hellopoland
datasource.database.password=hellopoland

hibernate.hbm2ddl.auto=create
hibernate.show.sql=false

przelewy24.confirmation.endpoint=https://sandbox.przelewy24.pl/trnVerify
przelewy24.crc=611e97ebd30f7be3
przelewy24.merchantId=71852
przelewy24.isSandbox=true

jwt.access.token.validity.millis=1800000
jwt.refresh.token.validity.millis=2592000000
jwt.access.token.secret.key=RqPW5zbChtPmzgSekctYdAWrHLNkBpDvK6meDtA3pDtAYKFBXH4UEjLvjdN9rfjkfS6LMpT2wvWvxg9kn38Fhw6qMSG2ZUzPx2tsrMcV8PsvCLx6BZVK5tLCakffCBy4
jwt.refresh.token.secret.key=D6KxAUe98wKdqkTrvNb2hYEtAaWnmjceX7mn7z7BruXmCmC3WUtCFQGxa3krhb9fcVfcy2TppCNKPWGjarbh6C5PdKzNWeNe3GDrP9rvsFt8dbJqWTFU3Am2NFnXSqLh

base.url=https://hpl.fream.pl/api/v1
hpt.cloud.url=http://localhost:8080/helloticket