datasource.name=bootstrap
datasource.driver=postgresql
datasource.database.host=localhost
datasource.database.port=5432
datasource.database.name=bootstrap
datasource.database.user=bootstrap
datasource.database.password=bootstrap

hibernate.hbm2ddl.auto=create

security.domain.name=bootstrap