wildfly.home=/home/hpl-prod/usr/wildfly
dms.root.path=/home/hpl-prod/var/DMS
datasource.database.name=hpl-prod
datasource.database.user=hpl-prod
datasource.database.password=hpl-prod
hibernate.hbm2ddl.auto=create
przelewy24.confirmation.endpoint=https://secure.przelewy24.pl/trnVerify
przelewy24.crc=