wildfly.home=C:\\Users\\kret\\workspaces\\HelloPoland\\HPL\\wildfly-13.0.0.Final
dms.root.path=C:\\Users\\kret\\workspaces\\HelloPoland\\HPL\\DMS
hibernate.hbm2ddl.auto=update

jwt.access.token.validity.millis=30000
jwt.refresh.token.validity.millis=30000