<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>pl.hellopoland</groupId>
		<artifactId>hellopoland</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>hellopoland.ejb</artifactId>
	<packaging>jar</packaging>
	<name>Hello Poland EJB</name>

	<dependencies>
		<!-- *LoginModule -->
		<dependency>
			<groupId>org.picketbox</groupId>
			<artifactId>picketbox</artifactId>
			<version>5.0.2.Final</version>
			<scope>provided</scope>
		</dependency>

		<!-- GoogleAPIConnector -->
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.23.0</version>
		</dependency>

		<!-- WooCommerceAPIConnector -->
		<dependency>
			<groupId>com.icoderman</groupId>
			<artifactId>wc-api-java</artifactId>
			<version>1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.2</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-dto</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>

</project>