<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>pl.hellopoland</groupId>
		<artifactId>hellopoland</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>hellopoland.ear</artifactId>
	<packaging>ear</packaging>
	<name>Hello Poland EAR</name>

	<dependencies>
		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland.ejb</artifactId>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland.rest</artifactId>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-dto</artifactId>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.parent.artifactId}</finalName>
		<plugins>
			<!-- EAR plug-in -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<!-- Tell Maven we are using Java EE -->
					<version>7</version>
					<!-- Use Java EE ear libraries as needed. Java EE ear libraries are 
						in easy way to package any libraries needed in the ear, and automatically 
						have any modules (EJB-JARs and WARs) use them -->
					<defaultLibBundleDir>lib</defaultLibBundleDir>
					<modules>
						<webModule>
							<groupId>pl.hellopoland</groupId>
							<artifactId>hellopoland.rest</artifactId>
							<contextRoot>/</contextRoot>
						</webModule>
					</modules>
					<outputFileNameMapping>@{artifactId}@-@{version}@.@{extension}@</outputFileNameMapping>
					<jboss>
						<version>5</version>
						<security-domain>${security.domain}</security-domain>
					</jboss>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>copy-wildfly-files</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.0.2</version>
						<executions>
							<execution>
								<phase>initialize</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>${wildfly.home}</outputDirectory>
									<resources>
										<resource>
											<directory>${project.build.directory}/classes/wildfly</directory>
											<filtering>false</filtering>
											<includes>
												<include>**/*.jar</include>
											</includes>
										</resource>
										<resource>
											<directory>${project.build.directory}/classes/wildfly</directory>
											<filtering>true</filtering>
											<excludes>
												<exclude>**/*.jar</exclude>
											</excludes>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>