wildfly.home=/home/fream/Pulpit/wildfly-11.0.0.Final
dms.root.path=/home/fream/Pulpit/Fream/Workspace/hellopoland/DMS
datasource.database.name=ww
datasource.database.user=ww
datasource.database.password=ww

hibernate.hbm2ddl.auto=create