wildfly.home=/home/hpl/usr/wildfly
dms.root.path=/home/hpl/var/DMS
datasource.database.name=hellopoland
datasource.database.user=hellopoland
datasource.database.password=hpl-prod
hibernate.hbm2ddl.auto=create

przelewy24.confirmation.endpoint=https://secure.przelewy24.pl/trnVerify
przelewy24.crc=ee0c1a05174cdbbc
przelewy24.merchantId=71852
przelewy24.isSandbox=false

base.url=https://api.hello-poland.pl/v1
