wildfly.home=/home/hpl/usr/wildfly
dms.root.path=/home/hpl/var/DMS
hibernate.hbm2ddl.auto=create
hpt.cloud.url=https://hpt.fream.pl/api

mail.username=tickets@hello-poland.pl
mail.password=gr34td34lHP
mail.smtp.host=hellopoland.nazwa.pl
mail.smtp.port=25
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory