wildfly.home=C:\\Users\\kret\\workspaces\\HelloPoland\\wildfly-14.0.1.Final
dms.root.path=C:\\Users\\kret\\workspaces\\HelloPoland\\wildfly-14.0.1.Final\\DMS
hibernate.hbm2ddl.auto=update
hpt.cloud.url=http://localhost:8180/helloticket

jwt.access.token.validity.millis=300000
jwt.refresh.token.validity.millis=300000