hibernate.hbm2ddl.auto=create
hibernate.show.sql=false
javax.persistence.jdbc.host=database
javax.persistence.jdbc.port=5433
javax.persistence.jdbc.database=hellopoland
javax.persistence.jdbc.user=hellopoland
javax.persistence.jdbc.password=hellopoland
