wildfly.home=C:\\Users\\lmrozek\\eclipse-workspace\\hpl\\wildfly-14.0.0.Final
dms.root.path=C:\\Users\\lmrozek\\eclipse-workspace\\hpl\\DMS

hibernate.hbm2ddl.auto=
hibernate.show.sql=true

jwt.access.token.validity.millis=3600000
jwt.refresh.token.validity.millis=300000

base.url=http://localhost:8080/hellopoland/v1
hpt.cloud.url=http://localhost:8180/helloticket
