<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>pl.fream</groupId>
		<artifactId>bootstrap</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>bootstrap.rest</artifactId>
	<packaging>war</packaging>
	<name>Fream Bootstrap REST</name>

	<dependencies>
		<dependency>
			<groupId>pl.fream</groupId>
			<artifactId>bootstrap.ejb</artifactId>
			<type>ejb</type>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>